name: CI
permissions:
  contents: read

on: [push]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Install Linux Packages
        if: matrix.os == 'ubuntu-latest'
        run: sudo apt-get update && sudo apt-get install gcc libgtk-3-dev libappindicator3-dev libwebkit2gtk-4.0-dev
      - uses: actions/setup-go@v2
        with:
          go-version: 1.16
      - uses: actions/checkout@v3.0.1
      - name: make
        run: make
