name: CI

on: [push]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Install Linux Packages
        if: matrix.os == 'ubuntu-latest'
        run: sudo apt-get update && sudo apt-get install gcc libgtk-3-dev libappindicator3-dev libwebkit2gtk-4.0-dev
      - uses: actions/setup-go@v2
        with:
          go-version: 1.15
      - uses: actions/checkout@v1
      - name: Initialize CodeQL
        uses: github/codeql-action/init@v1
        if: matrix.os == 'ubuntu-latest'
        with:
          languages: go
      - name: make
        run: make
      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v1
        if: matrix.os == 'ubuntu-latest'
