on:
  push:
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

name: Perform release
permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Install Linux Packages
        run: sudo apt-get update && sudo apt-get install gcc libgtk-3-dev libappindicator3-dev libwebkit2gtk-4.0-dev
      - uses: actions/setup-go@v2
        with:
          go-version: 1.15
      - uses: actions/checkout@v3.0.1
      - name: make
        run: make

  create_release:
    runs-on: ubuntu-latest
    needs: build # Check that the commit is actually buildable before creating the release
    outputs:
      upload_url: ${{ steps.create_release.outputs.upload_url }}
    steps:
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1.1.4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false

  release:
    needs: create_release

    strategy:
      matrix:
        config:
          - os: ubuntu-latest
            target: linux
            binary: linux
          - os: macos-latest
            target: mac
            binary: darwin

    runs-on: ${{ matrix.config.os }}

    steps:
      - name: Install Linux Packages
        if: matrix.config.os == 'ubuntu-latest'
        run: sudo apt-get update && sudo apt-get install gcc libgtk-3-dev libappindicator3-dev libwebkit2gtk-4.0-dev
      - uses: actions/setup-go@v2
        with:
          go-version: 1.15
      - uses: actions/checkout@v3.0.1
      - name: make
        run: make ${{ matrix.config.target }}
      - uses: actions/upload-release-asset@v1.0.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.create_release.outputs.upload_url }}
          asset_path: ./bin/release/aws_credential_expiration-${{ matrix.config.binary }}-amd64
          asset_name: aws_credential_expiration-${{ matrix.config.binary }}-amd64
          asset_content_type: application/octet-stream
