name: Security Scan

on:
  push:
    branches:
      - master
      - main
  pull_request:
  schedule:
    - cron: '0 13 * * 4'

jobs:
  security:

    runs-on: ubuntu-latest

    steps:
      - name: Install Linux Packages
        run: sudo apt-get update && sudo apt-get install gcc libgtk-3-dev libappindicator3-dev libwebkit2gtk-4.0-dev
      - name: Checkout Repository
        uses: actions/checkout@v3.2.0
      - name: Initialize CodeQL
        uses: github/codeql-action/init@v1
        with:
          languages: go
      - name: Autobuild
        uses: github/codeql-action/autobuild@v1
      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v1
